export const actions = {
  NOTIFICATION: "notification",
  CONTACT: "contact",

  LOGIN: "login",
  FORGOT_PASSWORD: "forgot_password",
  REGISTER: "register",
  RESET_PASSWORD: "reset_password",

  LOAD_DOCUMENTS: "LOAD_DOCUMENTS",
  LOAD_DOCUMENT: "LOAD_DOCUMENT",
  SEARCH_DOCUMENTS: "SEARCH_DOCUMENTS",

  ADMIN_CREATE_DOCUMENT: "ADMIN_CREATE_DOCUMENT",
  ADMIN_UPDATE_DOCUMENT: "ADMIN_UPDATE_DOCUMENT",
  ADMIN_DELETE_DOCUMENT: "ADMIN_DELETE_DOCUMENT",

  ADMIN_LOAD_USERS: "ADMIN_LOAD_USERS",
  ADMIN_UPDATE_USER: "ADMIN_UPDATE_USER",
  ADMIN_DELETE_USER: "ADMIN_DELETE_USER",

  ADMIN_LOAD_PURCHASES: "ADMIN_LOAD_PURCHASES",

  DOCUMENTS_LOAD_POPULAR: "DOCUMENTS_LOAD_POPULAR",

  PRE_PURCHASE_DOCUMENT: "PRE_PURCHASE_DOCUMENT",
  CHECK_PURCHASE_DOCUMENT: "CHECK_PURCHASE_DOCUMENT"
};

export const mutations = {
  LOADING: "LOADING",
  NOTIFICATION: "NOTIFICATION",

  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  USER: "USER",
  TOKEN: "TOKEN",

  DOCUMENTS: "DOCUMENTS",
  CURRENT_DOCUMENT: "CURRENT_DOCUMENT",
  POPULAR_DOCUMENTS: "POPULAR_DOCUMENTS",

  PURCHASES: "PURCHASES",
  CURRENT_PURCHASE: "CURRENT_PURCHASE",

  USERS: "USERS"
};
